apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith_to_microservices_udagram_frontend
  labels:
    app: monolith_to_microservices_udagram_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith_to_microservices_udagram_frontend
  template:
    metadata:
      labels:
        app: monolith_to_microservices_udagram_frontend
    spec:
      containers:
      - name: monolith_to_microservices_udagram_frontend
        image: mhayes30125/monolith_to_microservices_udagram_frontend:latest
        ports:
        - containerPort: 80