apiVersion: v1
kind: Service
metadata:
  name: monolith_to_microservices_udagram_frontend
  labels:
    run: monolith_to_microservices_udagram_frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: monolith_to_microservices_udagram_frontend