apiVersion: v1
kind: Service
metadata:
  name: monolith-to-microservices-udagram-frontend
  labels:
    app: monolith-to-microservices-udagram-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: monolith-to-microservices-udagram-frontend